<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>米家三合一切换器</AssemblyName>
    <RootNamespace>MiSwitcher</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <InvariantGlobalization>false</InvariantGlobalization>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Version>1.0.0</Version>
    <ProductName>米家游戏三合一切换器</ProductName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\genshin.png" />
    <Resource Include="Assets\starrail.png" />
    <Resource Include="Assets\zzz.png" />
  </ItemGroup>

</Project>
